### ISSUE TITLE
Автоустановка событий

### ISSUE THREAD

**Issue by loveorigami** [DevGroup-ru/yii2-events-system#1]
Интересный модуль. Подсмотрел пару идей )
Я в свое время делал тоже управление событиями, но в виде привычных плагинов.

Чтоб не создавать миграций - использовал phpDoc для автоустановки

Можете посмотреть тут
https://github.com/loveorigami/yii2-plugins-system

**Comment by bethrezen** [comment]
Миграции в реальном приложении быстрее phpDoc - обходить все файлы, коих может быть **ОЧЕНЬ** много - крайне затратно.
Если же ваш issue состоит только в этом - мы это делать точно не будем.

**Comment by loveorigami** [comment]
Не. Через phpDoc берутся данные для записи в бд только при установке плагина (евента) в плане пояснения - для чего этот евент нужен, какие задачи выполняет.
https://github.com/loveorigami/yii2-plugins-system/blob/master/docs/create_plugin.md

В результате получаем
https://github.com/loveorigami/yii2-plugins-system/blob/master/docs/install_plugin.md

**Comment by bethrezen** [comment]
А если обновили пакет? А если это в сторонних пакетах есть? Каждый раз прогонять по всем файлам в любом случае придётся и сопоставлять комментарии(вдруг они изменились). Нет, мы такое делать не будем.

**Comment by loveorigami** [comment]
Я просто хотел донести идею удобного добавления связки событие-обработчик в систему.
Скажем, пользователь, который захотел сделать подсветку кода у себя на сайте, вряд ли будет копаться в исходниках, искать к чему бы прицепить свой обработчик и где бы его взять...

Все замечания, которые вы написали выше, я сейчас реализовал в новой версии
https://github.com/loveorigami/yii2-plugins-system

- событие - уникальное, обработчик тоже уникальный. указал в композере точную версию, поставил себе плагин. 
- если предполагаю следить за обновлениями, значит ставлю не строгую зависимость. Если плагин обновился - на вкладке установок появится сообщение об обновлении плагина.

- да, чтобы сопоставить, что в базе и что в папках - приходится обходить. Но только при установке!
 у меня при 100 плагинах в 5 разных папках операция занимает <2 сек. Без кеширования.

- появилась также возможность проставить свое собственное событие и обработчик.
- а также отдельная ветка под систему - шорткоды.
https://github.com/loveorigami/yii2-shortcodes-pack

более детальный анонс
http://yiiframework.ru/forum/viewtopic.php?f=9&t=42209&p=208628&hilit=shortcode#p208625
